/** Compiles src/tokens/index.ts into src/web/styles/tokens.css. `--check` fails if the file is stale. */
import { densities, schemes, shared, tailwindColors } from '../src/tokens/index';

const OUT = new URL('../src/web/styles/tokens.css', import.meta.url);

const decl = (obj: Record<string, string>, indent = '  '): string =>
  Object.entries(obj)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join('\n');

const css = `/* GENERATED by scripts/build-tokens.ts from src/tokens/index.ts. Do not edit. */

:root {
${decl(shared)}
${decl(schemes.light)}
${decl(densities.comfortable)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${decl(schemes.dark, '    ')}
  }
}

[data-theme='dark'] {
${decl(schemes.dark)}
  color-scheme: dark;
}

[data-theme='light'] {
${decl(schemes.light)}
  color-scheme: light;
}

[data-density='comfortable'] {
${decl(densities.comfortable)}
}

[data-density='compact'] {
${decl(densities.compact)}
}

/* Touch defaults to the roomy ladder unless the app pins a density. */
@media (pointer: coarse) {
  :root:not([data-density]) {
${decl(densities.comfortable, '    ')}
  }
}

@media (min-resolution: 2dppx) {
  :root {
    --hairline: 0.5px;
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-scale: 0;
  }
}

@custom-variant dark {
  @media (prefers-color-scheme: dark) {
    &:not([data-theme='light'] *) {
      @slot;
    }
  }
  &:where([data-theme='dark'], [data-theme='dark'] *) {
    @slot;
  }
}

@theme inline {
${tailwindColors.map((c) => `  --color-${c}: var(--${c});`).join('\n')}
  --radius-xs: var(--radius-xs);
  --radius-sm: var(--radius-sm);
  --radius-md: var(--radius-md);
  --radius-lg: var(--radius-lg);
  --radius-xl: var(--radius-xl);
  --radius-2xl: var(--radius-2xl);
  --radius-control: var(--radius-control);
  --radius-field: var(--radius-field);
  --radius-surface: var(--radius-surface);
  --font-weight-control: var(--weight-control);
  --font-sans: var(--font-sans);
  --font-mono: var(--font-mono);
  --ease-snappy: var(--ease-snappy);
  --ease-out-quint: var(--ease-out-quint);
  --ease-in-cubic: var(--ease-in-cubic);
  --ease-out-cubic: var(--ease-out-cubic);
  --ease-standard: var(--ease-standard);
  --radius-dialog: var(--radius-dialog);
  --text-ui: var(--text-ui);
  --text-ui-sm: var(--text-ui-sm);
}
`;

const check = process.argv.includes('--check');
const file = Bun.file(OUT);
const current = (await file.exists()) ? await file.text() : '';
if (check) {
  if (current !== css) {
    console.error('tokens.css is stale. Run: bun run tokens');
    process.exit(1);
  }
  console.log('tokens.css is up to date');
} else {
  await Bun.write(OUT, css);
  console.log(`wrote ${OUT.pathname}`);
}
